export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
